site_name: VMPilot Documentation
docs_dir: docs/source
site_description: Documentation for VMPilot - AI-driven system operations assistant
theme:
  name: material
  features:
    - navigation.expand
    - toc.follow
    - search.highlight
    - search.share
    - content.code.copy

nav:
    - Home: index.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Getting Started: getting-started.md
    - Cost Tracking: cost-tracking.md
    - Using Open-WebUI: using-webui.md
    - Coding: coding.md
    - Git Tracking: git-tracking.md
    - Examples:
        - Overview: examples/index.md
        - Hello World: examples/hello-world.md
        - Fizzbuzz: examples/fizzbuzz.md
        - Github issue: examples/github-issue.md
        - Todo App 1: examples/todo1.md
        - Todo App 2: examples/todo2.md
    - Tools:
        - Google Search: tools/google-search.md
        - Claude Web Search: tools/web-search.md
    - Plugins:
        - Overview: plugins/overview.md
        - GitHub Issues: plugins/github.md
        - Testing Plugin: plugins/testing.md
        - Documentation Plugin: plugins/documentation.md
        - Project Plugin: plugins/project.md
        - Branch Manager Plugin: plugins/branch-manager.md
    - VMPilot Prompting: prompting.md
    - CLI Interface: cli.md
    - DNS and SSL: dns_ssl_setup.md
    - Release Process: release-process.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes

repo_url: https://github.com/drorm/vmpilot
edit_uri: edit/main/docs/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
