site_name: VMPilot Documentation
docs_dir: docs/source
site_description: Documentation for VMPilot - AI-driven system operations assistant
theme:
  name: material
  features:
    - navigation.expand
    - toc.follow
    - search.highlight
    - search.share
    - content.code.copy

nav:
    - Home: index.md
    - Installation: installation.md
    - Configuration: configuration.md
    - User Guide: user-guide.md
    - Git Tracking: git-tracking.md
    - Examples:
        - Overview: examples/index.md
        - Hello World: examples/hello-world.md
        - Fizzbuzz: examples/fizzbuzz.md
        - Github issue: examples/github-issue.md
        - Todo App 1: examples/todo1.md
        - Todo App 2: examples/todo2.md
        - Unit Testing: examples/unit_testing_example.md
    - Plugins:
        - Overview: plugins/overview.md
        - GitHub Plugin: plugins/github.md
        - Unit Testing Plugin: plugins/unit_testing.md
        - Documentation Plugin: plugins/documentation.md
    - VMPilot Prompting: prompting.md
    - Tips: tips.md
    - CLI Interface: cli.md
    - DNS and SSL: dns_ssl_setup.md
    - Release Process: release-process.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes

repo_url: https://github.com/drorm/vmpilot
edit_uri: edit/main/docs/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
