name: Bug Report
description: Report a problem with the application.
body:
  - type: markdown
    attributes:
      value: |
        Please fill out all sections.
  - type: input
    id: title
    attributes:
      label: Bug Title
      placeholder: A short summary of the bug
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
