version: '3.8'

services:
  vmpilot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "9099:9099"
      - "8080:8080"
    volumes:
      - ../config:/app/config:ro
      - vmpilot_data:/app/data
    environment:
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9099/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  vmpilot_data:

