site_name: VMPilot Documentation
docs_dir: source
site_description: Documentation for VMPilot - AI-driven system operations assistant
theme:
  name: material
  features:
    - navigation.sections
    - toc.follow
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - User Guide: user-guide.md
  - Plugins: plugins.md
  - VMPilot Prompting: prompting.md
  - Tips: tips.md
  - CLI Interface: cli.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes

repo_url: https://github.com/your-repo/vmpilot
edit_uri: edit/main/docs/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
